package xyz.cybersapien.jokes;

import android.support.constraint.ConstraintLayout;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    List<Joke> jokeList;
    LinearLayout rootLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        jokeList = new ArrayList<>();

        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));

        ListView listView = findViewById(R.id.list_view);
        JokeAdapter adapter = new JokeAdapter(this, jokeList);
        listView.setAdapter(adapter);

    }
}
