package xyz.cybersapien.jokes;

import android.support.constraint.ConstraintLayout;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    ArrayList<Joke> jokeList;
    LinearLayout rootLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        jokeList = new ArrayList<>();

        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));
        jokeList.add(new Joke("Manmeet", "Instructor", "people"));
        jokeList.add(new Joke("Hello", "Hi", "Ana"));

//        "https://github.com/DSC-Chitkara/jokes-list-sample"

        RecyclerView recyclerView = findViewById(R.id.list_view);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        JokeRecyclerAdapter adapter = new JokeRecyclerAdapter(jokeList, this);
        recyclerView.setAdapter(adapter);

    }
}
